### ISSUE TITLE
load extension

### ISSUE THREAD

**Issue by IGNick** [xNinjaKittyx/ChitogeBot#26]
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python36-32\bot.py", line 209, in <module>
    bot.load_extension(x)
  File "C:\Users\*\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "C:\Users\*\AppData\Local\Programs\Python\Python36-32\modules\anime.py", line 187, in setup
    bot.add_cog(Anime(bot))
  File "C:\Users\*\AppData\Local\Programs\Python\Python36-32\modules\anime.py", line 41, in __init__
    self.access_token, self.lastaccess = self.getaccesstoken()
TypeError: 'NoneType' object is not iterable
>>>

**Comment by xNinjaKittyx** [comment]
This bot is outdated and is not compliant with the newest versions of discord.py

This program shouldn't be used live.
I will update this respository in the future to be a basic framework for people who want to build a bot of their own.

**Comment by IGNick** [comment]
oh, what old version can be used for this bot?

**Comment by xNinjaKittyx** [comment]
I honestly can't tell you because the last time I touched this bot way too long ago.
Why do you need to run this bot? For what purpose?

**Comment by IGNick** [comment]
You coded a nice bot, This is the kind of bot i was looking for than the rest.

**Comment by xNinjaKittyx** [comment]
If you just want a bot on your server, you can invite that bot to your server.

If you want to code a bot, you should consider reading the API and coding it from scratch. You will learn more out of that.  Of course, you're always welcome to see the code and learn from it as well.

**Comment by IGNick** [comment]
Thanks, i don't only want a bot on my server, but i want a bot that i can edit and so on from there, and not claiming i'm the creator of it. Sure, i'll check out the API.
